#!/usr/bin/env python3
"""Turn the physical tire-storage inventory take into data/inventory.js.

The transcription of the count lives in tools/inventory_rows.py (edit that
after each stocktake, then re-run this script).  The original hand-written
sheet is kept alongside the data as provenance.

Usage:  python3 tools/convert_inventory.py [output_dir]
"""
import json, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from inventory_rows import ROWS

COLS = ["loc", "cont", "name", "plate", "vehicle", "tires", "rims",
        "lastSwap", "seasons", "note"]
COUNT_DATE = "2026-08"          # when the count was taken
CONTAINERS = "Container A + B"


def main(out_dir="data"):
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "inventory.js")
    with open(path, "w", encoding="utf-8") as f:
        f.write("// Physical tire-storage inventory. Generated by "
                "tools/convert_inventory.py - do not edit by hand.\n")
        f.write('window.TP_INVENTORY = {\n"countDate": %s,\n"scope": %s,\n"cols": %s,\n"rows": [\n'
                % (json.dumps(COUNT_DATE), json.dumps(CONTAINERS), json.dumps(COLS)))
        f.write(",\n".join(json.dumps(r, ensure_ascii=False, separators=(",", ":")) for r in ROWS))
        f.write("\n]};\n")
    occupied = sum(1 for r in ROWS if r[2].upper() != "OPEN SPOT")
    print("wrote %s (%d slots, %d occupied)" % (path, len(ROWS), occupied))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "data")
