#!/usr/bin/env python3
"""Convert Workshop Software CSV exports into the JS data files used by the app.

Usage:
    python3 tools/convert_csv.py <invoices.csv> <invoice_items.csv> [output_dir]

Writes data/invoices.js and data/items.js (JS files that assign to a global
variable so the app can load them over file:// without fetch/CORS issues).
"""
import csv, html, json, re, sys, os

csv.field_size_limit(10**9)

INV_COLS = ["job","inv","type","status","date","name","plate","desc","total",
            "balance","gst","subtotal","discount","deposits","taxRate","state",
            "suburb","postcode","make","model","buildDate","bodyType","odometer",
            "note","jobNote"]
ITEM_COLS = ["job","code","desc","qty","unitPrice","gst","amount","sub","ptype","ordering","bom","note"]


def num(v):
    v = (v or "").strip()
    if not v:
        return None
    try:
        f = float(v)
    except ValueError:
        return None
    return int(f) if f == int(f) and abs(f) < 1e15 else round(f, 6)


def s(v):
    return (v or "").strip()


def plain(v):
    """HTML note -> plain text with newlines (notes are stored as <p>..</p> HTML)."""
    t = re.sub(r"<\s*(?:br|/p|/div|/li)[^>]*>", "\n", v or "", flags=re.I)
    t = re.sub(r"<[^>]+>", "", t)
    t = html.unescape(t)
    t = re.sub(r"[ \t]+", " ", t)
    t = re.sub(r"\n\s*\n+", "\n", t)
    return t.strip()


def convert(inv_csv, item_csv, out_dir):
    inv_rows = []
    with open(inv_csv, encoding="utf-8-sig", newline="") as f:
        for r in csv.DictReader(f):
            inv_rows.append([
                num(r["job_card_number"]) or s(r["job_card_number"]),
                num(r["invoice_number"]) or (s(r["invoice_number"]) or None),
                s(r["invoice_type"]), s(r["invoice_status"]), s(r["post_date"]),
                s(r["display_name"]), s(r["plate_number"]), s(r["description"]),
                num(r["total"]), num(r["balance_due"]), num(r["gst"]),
                num(r["subtotal"]), num(r["discount_total"]), num(r["deposits_total"]),
                num(r["tax_rate"]), s(r["state"]), s(r["suburb"]), s(r["postcode"]),
                s(r["make"]), s(r["model"]), s(r["build_date"]), s(r["body_type"]),
                num(r["odometer"]), plain(r["note"]), plain(r["job_card_note"]),
            ])

    item_rows = []
    with open(item_csv, encoding="utf-8-sig", newline="") as f:
        for r in csv.DictReader(f):
            item_rows.append([
                num(r["job_card_number"]) or s(r["job_card_number"]),
                s(r["item_code"]), s(r["description"]) or s(r["product_description"]),
                num(r["quantity"]), num(r["unit_price"]), num(r["gst"]),
                num(r["amount"]), num(r["subtotal"]), s(r["product_type"]),
                num(r["ordering"]), 1 if s(r["is_bom_parent"]) == "true" else 0,
                s(r["note"]),
            ])

    os.makedirs(out_dir, exist_ok=True)

    def write(name, var, cols, rows):
        path = os.path.join(out_dir, name)
        with open(path, "w", encoding="utf-8") as f:
            f.write("// Generated by tools/convert_csv.py - do not edit by hand.\n")
            f.write("window.%s = {\n\"cols\": %s,\n\"rows\": [\n" % (var, json.dumps(cols)))
            f.write(",\n".join(json.dumps(r, ensure_ascii=False, separators=(",", ":")) for r in rows))
            f.write("\n]};\n")
        print("wrote %s (%d rows, %.1f MB)" % (path, len(rows), os.path.getsize(path) / 1e6))

    write("invoices.js", "TP_INVOICES", INV_COLS, inv_rows)
    write("items.js", "TP_ITEMS", ITEM_COLS, item_rows)


if __name__ == "__main__":
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    convert(sys.argv[1], sys.argv[2], sys.argv[3] if len(sys.argv) > 3 else "data")
